name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
          
    - name: Go modules cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
              
    - name: Run golangci-lint
      if: github.ref != 'refs/heads/main'
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: v1.29

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
